[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Root topic

## CBrain

### AIEntityWorkingData

#### CTransform2D entityTF

#### CAnimatorView EntityAnimatorView

##### 为什么同时使用Animation和Animator？<br/>demo 主角用的是Animation 小怪用的是Animator

### CAnimation

## 下面大量C开头的类是Character的意思？<br/>应该是Component
> leftSide=`true`


## CTransform2D
> leftSide=`true`


### 2D的Transform ?

## BaseEntity

### 基本实体，有属性，生命周期，基本组件管理

### Player

#### 拓展BaseEntity,处理技能发射和输入控制

## CMover
> leftSide=`true`


### 位置和朝向更新组件

## 输入处理和技能触发

### 玩家对象身上的CSkill脚本决定有哪些技能

#### zhu

### SkillPart 列表指定当前技能有哪些效果

### Player\.DoUpdate
